name: Style Checker
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Style Checker Job
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/pycodestyle
      - name: Python Style Checker
        uses: andymckay/pycodestyle-action@0.1.3
  
# https://github.com/marketplace/actions/run-flake8-on-your-pr-with-annotations?version=1.0.1
# workflow "on check suite creation, run flake8 and post results" {
#     on = "pull_request"
#     resolves = "run flake8"}
# action "run flake8" {
#     uses = "tayfun/flake8-your-pr@master"
#     secrets = ["GITHUB_TOKEN"]
# }
